import type { LevelId } from "./curriculum";
export type SimulationId = "force" | "projectile" | "pendulum" | "wave" | "refraction" | "circuit" | "heat" | "quantum";
export interface Simulation { id: SimulationId; title: string; question: string; topic: string; icon: string; levels: LevelId[]; observe: string; theory: string; formula: string; assumptions: string; challenge: string; source: string; }
export const simulations: Simulation[] = [
{ id:"force",title:"ผลักเท่ากัน ทำไมไปไม่เท่ากัน?",question:"เปลี่ยนแรงและมวล แล้วเปรียบเทียบการเคลื่อนที่",topic:"แรงและการเคลื่อนที่",icon:"→",levels:["elementary","middle-school","high-school"],observe:"คงแรงไว้แล้วเพิ่มมวล สังเกตระยะที่เคลื่อนไปในเวลาเท่ากัน",theory:"แรงลัพธ์ทำให้ความเร็วเปลี่ยน มวลมากขึ้นจะมีความเร่งน้อยลงเมื่อรับแรงลัพธ์เท่าเดิม",formula:"a = F/m · x = ½at² · v = at",assumptions:"เริ่มนิ่ง แรงแนวนอนคงที่ ไม่มีแรงเสียดทาน ทดลองครั้งละ 3 วินาที",challenge:"เพิ่มมวลสองเท่า ต้องเพิ่มแรงกี่เท่าจึงได้ความเร่งเดิม?",source:"https://openstax.org/books/university-physics-volume-1/pages/5-3-newtons-second-law"},
{ id:"projectile",title:"ยิงมุมไหน ไปได้ไกลที่สุด?",question:"เปลี่ยนมุม ความเร็ว และแรงโน้มถ่วง แล้วดูวิถีลูกบอล",topic:"แรงและการเคลื่อนที่",icon:"↗",levels:["elementary","middle-school","high-school","university"],observe:"ลองมุม 30° และ 60° ด้วยความเร็วเท่ากัน เปรียบเทียบระยะทางกับเวลาบิน",theory:"แนวราบกับแนวดิ่งใช้เวลาเดียวกัน แนวราบเร็วคงที่ ส่วนแนวดิ่งมีความเร่งจากแรงโน้มถ่วง",formula:"x = v₀cosθ·t · y = v₀sinθ·t − ½gt²",assumptions:"ไม่มีแรงต้านอากาศ g คงที่ จุดเริ่มและจุดตกสูงเท่ากัน กราฟปรับสเกลอัตโนมัติ",challenge:"เหตุใด 45° ให้ระยะสูงสุดเมื่อจุดเริ่มและจุดตกอยู่ระดับเดียวกัน?",source:"https://openstax.org/books/university-physics-volume-1/pages/4-3-projectile-motion"},
{ id:"pendulum",title:"ลูกตุ้มยาวขึ้น แกว่งช้าลงไหม?",question:"เปลี่ยนความยาว มวล และแรงโน้มถ่วง แล้วจับจังหวะ",topic:"การสั่นและคลื่น",icon:"◡",levels:["elementary","middle-school","high-school","university"],observe:"เพิ่มมวลโดยคงความยาว แล้วเปรียบเทียบกับการเพิ่มความยาว",theory:"สำหรับมุมเล็ก คาบขึ้นกับความยาวและแรงโน้มถ่วง แต่ไม่ขึ้นกับมวล ลูกตุ้มยาวขึ้นจึงแกว่งช้าลง",formula:"T ≈ 2π√(L/g) · θ(t) ≈ θ₀cos(√(g/L)t)",assumptions:"มวลจุด เชือกไร้มวล ไม่มีแรงต้าน ใช้การประมาณมุมเล็กไม่เกิน 15°",challenge:"ถ้าต้องการให้คาบเพิ่มสองเท่า ต้องเพิ่มความยาวเป็นกี่เท่า?",source:"https://openstax.org/books/university-physics-volume-1/pages/15-4-pendulums"},
{ id:"wave",title:"คลื่นเดินทาง แต่ตัวกลางไปไหน?",question:"เปลี่ยนความถี่และความเร็ว แล้วดูจุดบนตัวกลาง",topic:"การสั่นและคลื่น",icon:"∿",levels:["elementary","middle-school","high-school","university"],observe:"จุดสีส้มอยู่ตำแหน่งแนวราบเดิม แต่ยอดคลื่นเดินไปทางขวา",theory:"คลื่นส่งการรบกวนผ่านตัวกลาง ส่วนอนุภาคสั่นรอบตำแหน่งเดิม เมื่อความเร็วคงที่ ความถี่มากขึ้นทำให้ความยาวคลื่นสั้นลง",formula:"v = fλ · y = A sin[2π(x/λ − ft)]",assumptions:"คลื่นตามขวางรูปไซน์ ตัวกลางอุดมคติ ไม่มีการหน่วง แกนแสดงระยะเป็นเมตร",challenge:"เพิ่มความถี่สองเท่าโดยไม่เปลี่ยนความเร็ว ความยาวคลื่นเปลี่ยนอย่างไร?",source:"https://openstax.org/books/university-physics-volume-1/pages/16-2-mathematics-of-waves"},
{ id:"refraction",title:"แสงเลี้ยวที่รอยต่ออย่างไร?",question:"สลับอากาศ น้ำ และแก้ว แล้วปรับมุมตกกระทบ",topic:"แสง",icon:"↘",levels:["middle-school","high-school","university"],observe:"ส่งแสงจากแก้วสู่อากาศแล้วเพิ่มมุม ดูจุดที่รังสีหักเหหายไป",theory:"แสงเปลี่ยนทิศเมื่อดัชนีหักเหต่างกัน หากจากดัชนีมากไปน้อยและมุมเกินมุมวิกฤต จะสะท้อนกลับหมด",formula:"n₁sinθ₁ = n₂sinθ₂ · θc = arcsin(n₂/n₁) เมื่อ n₁ > n₂",assumptions:"ผิวเรียบ ตัวกลางโปร่งใส มุมวัดจากเส้นตั้งฉาก แสดงทิศรังสี ไม่ได้แสดงความเข้ม",challenge:"ส่งแสงจากอากาศเข้าแก้วจะเกิดการสะท้อนกลับหมดได้หรือไม่?",source:"https://openstax.org/books/university-physics-volume-3/pages/1-4-total-internal-reflection"},
{ id:"circuit",title:"ต่อวงจรต่างกัน กระแสต่างไหม?",question:"สลับอนุกรมกับขนาน ปรับแรงดันและความต้านทาน",topic:"ไฟฟ้า",icon:"ϟ",levels:["middle-school","high-school","university"],observe:"ดูกระแสแต่ละแขนงและกระแสรวม หลังเปลี่ยนชนิดวงจร",theory:"อนุกรมมีกระแสเท่ากันและความต้านทานบวกกัน ขนานมีแรงดันเท่ากันแต่กระแสแบ่งตามความต้านทาน",formula:"I = V/R · Rอนุกรม = R₁+R₂ · 1/Rขนาน = 1/R₁+1/R₂",assumptions:"ตัวต้านทานโอห์มมิก แหล่งจ่ายและสายไฟอุดมคติ จุดเคลื่อนที่เป็นสัญลักษณ์กระแส ไม่ใช่ความเร็วอิเล็กตรอนจริง",challenge:"เพิ่ม R₁ ในวงจรขนาน กระแสผ่าน R₂ เปลี่ยนหรือไม่?",source:"https://openstax.org/books/university-physics-volume-2/pages/10-2-resistors-in-series-and-parallel"},
{ id:"heat",title:"ผสมน้ำแล้วจะได้กี่องศา?",question:"ปรับมวลและอุณหภูมิสองแก้ว ดูผลการผสมทันที",topic:"ความร้อน",icon:"≋",levels:["elementary","middle-school","high-school"],observe:"ผสมน้ำมวลเท่ากัน แล้วเพิ่มมวลแก้วที่ร้อนกว่า",theory:"น้ำอุ่นเสียพลังงานให้น้ำเย็นจนมีอุณหภูมิสมดุล เมื่อมวลไม่เท่ากัน อุณหภูมิสุดท้ายใกล้แก้วที่มีมวลมากกว่า",formula:"Tf = (m₁T₁+m₂T₂)/(m₁+m₂) สำหรับน้ำที่มี c เท่ากัน",assumptions:"ไม่มีการเปลี่ยนสถานะ ไม่เสียความร้อนให้ภาชนะหรืออากาศ แสดงก่อนและหลังสมดุล ไม่จำลองเวลาผสม",challenge:"น้ำ 80°C กับน้ำ 20°C ต้องมีสัดส่วนมวลเท่าไรจึงได้ 40°C?",source:"https://openstax.org/books/university-physics-volume-2/pages/1-4-heat-transfer-specific-heat-and-calorimetry"},
{ id:"quantum",title:"อนุภาคในกล่องอยู่ตรงไหนได้บ้าง?",question:"เลือกระดับพลังงานและขนาดกล่อง แล้วดูโอกาสพบอนุภาค",topic:"ควอนตัม",icon:"ψ",levels:["high-school","university"],observe:"เพิ่มเลขควอนตัมแล้วนับจุดศูนย์ ลองเปลี่ยนขนาดกล่องและดูพลังงาน",theory:"สถานะพลังงานแน่นอนในบ่อศักย์อนันต์มีความหนาแน่นความน่าจะเป็นไม่เปลี่ยนตามเวลา ภาพนี้ไม่ใช่วิถีการวิ่งของอนุภาค",formula:"ψₙ = √(2/L)sin(nπx/L) · Eₙ = n²h²/(8mL²)",assumptions:"อิเล็กตรอนหนึ่งตัว บ่ออนันต์หนึ่งมิติ ไม่สัมพัทธภาพ แกนนอนใช้ x/L แกนตั้ง L|ψ|²",challenge:"เพิ่มความกว้างกล่องสองเท่า พลังงานของสถานะเดิมลดกี่เท่า?",source:"https://openstax.org/books/university-physics-volume-3/pages/7-4-the-quantum-particle-in-a-box"}
];
export const simulationHref = (id: SimulationId) => `/simulations/${id}/`;
