"use client";
import { useEffect, useId, useState, type ReactNode } from "react";
export function useClock(limit=Infinity){
 const [time,setTime]=useState(0),[playing,setPlaying]=useState(false);const running=playing&&time<limit;
 useEffect(()=>{if(!running)return;let frame:number;let last:number|undefined;function tick(now:number){const dt=last===undefined?0:Math.min((now-last)/1000,0.05);last=now;setTime(t=>Math.min(limit,t+dt));frame=requestAnimationFrame(tick);}frame=requestAnimationFrame(tick);return()=>cancelAnimationFrame(frame);},[running,limit]);
 return {time,running,toggle:()=>{if(time>=limit)setTime(0);setPlaying(!running);},reset:()=>{setTime(0);setPlaying(false);}};
}
export function Slider({label,value,min,max,step=1,unit="",onChange}:{label:string;value:number;min:number;max:number;step?:number;unit?:string;onChange:(v:number)=>void}){const id=useId();return <div className="sim-slider"><label htmlFor={id}>{label}<output>{value} {unit}</output></label><input id={id} type="range" min={min} max={max} step={step} value={value} onChange={e=>onChange(Number(e.target.value))}/></div>;}
export function Playback({clock}:{clock:ReturnType<typeof useClock>}){return <div className="playback"><button className="button" onClick={clock.toggle}>{clock.running?"หยุดชั่วคราว Ⅱ":"เริ่มจำลอง ▶"}</button><button className="mode-button" onClick={clock.reset}>เริ่มเวลาใหม่ ↺</button></div>;}
export function Frame({title,children,controls,stats,note}:{title:string;children:ReactNode;controls:ReactNode;stats:[string,string][];note?:string}){return <div className="lab"><div className="lab-visual"><div className="lab-top"><span>{title}</span><span>ปรับค่าแล้วดูผล</span></div><svg className="physics-stage" viewBox="0 0 720 400" role="img" aria-label={title}>{children}</svg>{note&&<p className="muted">{note}</p>}<div className="stats">{stats.map(([label,value])=><div key={label}><strong>{value}</strong><span>{label}</span></div>)}</div></div><div className="controls"><h2>ลองเปลี่ยนเงื่อนไข</h2>{controls}</div></div>;}
export function Arrow({x1,y1,x2,y2,color="#c96038"}:{x1:number;y1:number;x2:number;y2:number;color?:string}){const a=Math.atan2(y2-y1,x2-x1);if(Math.hypot(x2-x1,y2-y1)<0.1)return null;return <g><line x1={x1} y1={y1} x2={x2} y2={y2} stroke={color} strokeWidth="3"/><polygon points={`${x2},${y2} ${x2-10*Math.cos(a-0.45)},${y2-10*Math.sin(a-0.45)} ${x2-10*Math.cos(a+0.45)},${y2-10*Math.sin(a+0.45)}`} fill={color}/></g>;}
