"use client";
import { useEffect, useState } from "react";
import { projectile } from "@/simulations/mechanics/projectile";
export function ProjectileLab() {
 const [speed, setSpeed] = useState(20), [angle, setAngle] = useState(45), [gravity, setGravity] = useState(9.81), [time, setTime] = useState(0), [playing, setPlaying] = useState(false);
 const model = projectile({ speed, angle, gravity });
 useEffect(() => { if (!playing) return; let frame: number; let previous: number | undefined; const tick = (now: number) => { const delta = previous === undefined ? 0 : Math.min((now - previous) / 1000, 0.1); previous = now; setTime(t => Math.min(model.duration, t + delta)); frame = requestAnimationFrame(tick); }; frame = requestAnimationFrame(tick); return () => cancelAnimationFrame(frame); }, [playing, model.duration]);
 const finished = time >= model.duration;
 useEffect(() => { if (finished && playing) { const id = setTimeout(() => setPlaying(false), 0); return () => clearTimeout(id); } }, [finished, playing]);
 const scale = Math.min(620 / Math.max(model.range, 10), 240 / Math.max(model.height, 5));
 const point = model.position(time);
 const path = Array.from({ length: 81 }, (_, i) => { const p = model.position(model.duration * i / 80); return `${40 + p.x * scale},${290 - p.y * scale}`; }).join(" ");
 function reset() { setPlaying(false); setTime(0); }
 return <div className="lab"><div className="lab-visual"><div className="lab-top"><span>01 / PROJECTILE MOTION</span><span>t = {time.toFixed(2)} s</span></div><svg viewBox="0 0 720 340" role="img" aria-label="กราฟวิถีลูกบอล แกนนอนเป็นระยะทาง แกนตั้งเป็นความสูง"><defs><pattern id="grid" width="30" height="30" patternUnits="userSpaceOnUse"><path d="M 30 0 L 0 0 0 30" fill="none" stroke="#dce4df" strokeWidth="1"/></pattern></defs><rect x="40" y="20" width="650" height="270" fill="url(#grid)"/><path d="M40 20V290H690" fill="none" stroke="#7f9588"/><polyline points={path} fill="none" stroke="#92b4a0" strokeWidth="2" strokeDasharray="6 6"/><circle cx={40 + point.x * scale} cy={290 - point.y * scale} r="10" fill="#de754e"/><text x="45" y="325">0</text><text x="460" y="325">ระยะทาง (m) · ปลายวิถี {model.range.toFixed(1)}</text><text x="50" y="16">ความสูง (m)</text></svg><p className="muted">กราฟปรับสเกลอัตโนมัติ · ไม่คิดแรงต้านอากาศ · จุดเริ่มและจุดตกสูงเท่ากัน</p><div className="stats"><div><strong>{model.range.toFixed(1)} m</strong><span>ระยะทางแนวราบ</span></div><div><strong>{model.height.toFixed(1)} m</strong><span>ความสูงสูงสุด</span></div><div><strong>{model.duration.toFixed(2)} s</strong><span>เวลาทั้งหมด</span></div></div></div><div className="controls"><h2>ลองเปลี่ยนเงื่อนไข</h2><label htmlFor="speed">ความเร็วเริ่มต้น <strong>{speed} m/s</strong></label><input id="speed" type="range" min="5" max="40" value={speed} onChange={e => { reset(); setSpeed(Number(e.target.value)); }}/><label htmlFor="angle">มุมยิง <strong>{angle}°</strong></label><input id="angle" type="range" min="5" max="85" value={angle} onChange={e => { reset(); setAngle(Number(e.target.value)); }}/><label htmlFor="gravity">แรงโน้มถ่วง</label><select id="gravity" value={gravity} onChange={e => { reset(); setGravity(Number(e.target.value)); }}><option value="9.81">โลก · 9.81 m/s²</option><option value="1.62">ดวงจันทร์ · 1.62 m/s²</option><option value="3.71">ดาวอังคาร · 3.71 m/s²</option></select><button className="button" onClick={() => { if (finished) setTime(0); setPlaying(!playing); }}>{playing ? "หยุดชั่วคราว" : finished ? "ทดลองอีกครั้ง ↗" : "เริ่มการทดลอง ▶"}</button><button className="reset" onClick={reset}>เริ่มเวลาใหม่ ↺</button><div className="hint"><strong>ชวนคิด</strong><p>ถ้าความเร็วเท่าเดิม มุม 30° และ 60° จะให้ระยะทางต่างกันไหม?</p></div></div></div>;
}
