"use client";
import { WebSwingLab } from "./web-swing-lab";
import { useState } from "react";
import { useClock, Slider, Playback, Frame, Arrow } from "./lab-primitives";
import { CoasterLab, BuoyancyLab, OrbitLab } from "./discovery-labs";
import { ThreeBodyLab } from "./three-body-lab";
import { TorricelliLab, YoungLab, RutherfordLab } from "./scientist-labs";
import { SpectrumLab } from "./spectrum-lab";
import { ElementsLab } from "./elements-lab";
import { OsmosisLab, AcidBaseLab } from "./life-labs";
import {
  InclineLab, CollisionLab, LensLab, MotorLab, HalfLifeLab, EnzymeLab, PhotosynthesisLab,
  MendelLab, PredatorPreyLab, ReactionRateLab, EquilibriumLab, IdealGasLab, TitrationLab,
  BrakingLab, LiftLab, TorqueLab, PressureLab,
} from "./extra-labs";
import { LinearLab, QuadraticLab, ExponentialLab, AbsoluteLab, ReciprocalLab, TrigonometryLab, ProbabilityLab, AreaLab } from "./math-labs";
import {
  DopplerLab, CoulombLab, ConductionLab, DnaLab, SineLab, FoucaultLab, BrownianLab, OerstedLab,
} from "./more-labs";
import { MagnetLab, LorentzLab, FaradayLab } from "./magnetism-labs";
import { BondLab, IonicLab, LewisLab } from "./bonding-labs";
import { forceMotion, pendulumPeriod, waveDisplacement, refractedAngle, resistorCircuit, mixedTemperature, boxEnergyEV, boxDensity, boxProbability } from "@/simulations/models";
import type { SimulationId } from "@/content/simulations";
function ForceLab(){
 const [force,setForce]=useState(10),[mass,setMass]=useState(2);const clock=useClock(3),model=forceMotion(force,mass,clock.time),x=50+model.distance*6;
 return <Frame title="แรงลัพธ์กับการเคลื่อนที่" stats={[["ความเร่ง",`${model.acceleration.toFixed(2)} m/s²`],["ระยะทาง",`${model.distance.toFixed(2)} m`],["เวลา",`${clock.time.toFixed(2)} s`]]} controls={<><Slider label="แรงผลัก" value={force} min={0} max={20} unit="N" onChange={v=>{clock.reset();setForce(v);}}/><Slider label="มวล" value={mass} min={1} max={10} unit="kg" onChange={v=>{clock.reset();setMass(v);}}/><Playback clock={clock}/><p className="muted">เริ่มนิ่ง ไม่มีแรงเสียดทาน · สเกลระยะคงที่</p></>}>
 <line x1="50" y1="290" x2="670" y2="290" stroke="#7c9682"/>{[0,25,50,75,100].map(d=><g key={d}><line x1={50+d*6} y1="285" x2={50+d*6} y2="300" stroke="#7c9682"/><text x={50+d*6} y="326" textAnchor="middle">{d} m</text></g>)}<rect x={x-23} y="240" width="46" height="44" rx="7" fill="#345e48"/><circle cx={x-13} cy="285" r="7" fill="#1c392c"/><circle cx={x+13} cy="285" r="7" fill="#1c392c"/><text x={x} y="267" textAnchor="middle" className="inverse-text">{mass} kg</text><Arrow x1={x} y1={215} x2={x+force*2} y2={215}/><text x={x} y="193" textAnchor="middle">F = {force} N</text><text x="50" y="60">v = {model.velocity.toFixed(2)} m/s</text><text x="50" y="95">{force===0?"แรงลัพธ์ศูนย์: วัตถุที่เริ่มนิ่งยังอยู่นิ่ง":"แรงมากขึ้น → ความเร็วเพิ่มเร็วขึ้น"}</text></Frame>;
}
function PendulumLab(){
 const [length,setLength]=useState(1.5),[mass,setMass]=useState(1),[gravity,setGravity]=useState(9.81),[amplitude,setAmplitude]=useState(12);const clock=useClock();const angle=amplitude*Math.PI/180*Math.cos(Math.sqrt(gravity/length)*clock.time),rope=length*85,x=360+rope*Math.sin(angle),y=55+rope*Math.cos(angle);
 return <Frame title="ลูกตุ้มอย่างง่าย: การประมาณมุมเล็ก" stats={[["คาบ",`${pendulumPeriod(length,gravity).toFixed(2)} s`],["มุมขณะนี้",`${(angle*180/Math.PI).toFixed(1)}°`],["เวลา",`${clock.time.toFixed(1)} s`]]} controls={<><Slider label="ความยาวเชือก" value={length} min={0.3} max={3} step={0.1} unit="m" onChange={v=>{clock.reset();setLength(v);}}/><Slider label="มวลลูกตุ้ม" value={mass} min={0.2} max={3} step={0.2} unit="kg" onChange={setMass}/><Slider label="มุมเริ่มต้น" value={amplitude} min={3} max={15} unit="°" onChange={v=>{clock.reset();setAmplitude(v);}}/><label htmlFor="pendulum-gravity">แรงโน้มถ่วง</label><select id="pendulum-gravity" value={gravity} onChange={e=>{clock.reset();setGravity(Number(e.target.value));}}><option value="9.81">โลก · 9.81 m/s²</option><option value="1.62">ดวงจันทร์ · 1.62 m/s²</option></select><Playback clock={clock}/></>} note="ขนาดลูกตุ้มแทนมวลเชิงสัญลักษณ์ · ความยาวเชือกใช้สเกลคงที่">
 <line x1="290" y1="48" x2="430" y2="48" stroke="#345e48" strokeWidth="8"/><line x1="360" y1="55" x2="360" y2="340" stroke="#a6b4a5" strokeDasharray="5 5"/><line x1="360" y1="55" x2={x} y2={y} stroke="#345e48" strokeWidth="3"/><circle cx="360" cy="55" r="5" fill="#345e48"/><circle cx={x} cy={y} r={12+Math.sqrt(mass)*6} fill="#d87951"/><text x="60" y="365">เพิ่มมวล → คาบเท่าเดิม · เพิ่มความยาว → คาบมากขึ้น</text></Frame>;
}
function WaveLab(){
 const [frequency,setFrequency]=useState(1),[speed,setSpeed]=useState(3),[amplitude,setAmplitude]=useState(0.6);const clock=useClock(),wavelength=speed/frequency;
 const points=Array.from({length:301},(_,i)=>{const x=i/300*12;return `${50+x*50},${200-waveDisplacement(x,clock.time,amplitude,frequency,speed)*100}`;}).join(" ");
 return <Frame title="คลื่นตามขวาง: จุดสีส้มคืออนุภาคหนึ่งจุด" stats={[["ความยาวคลื่น",`${wavelength.toFixed(2)} m`],["คาบ",`${(1/frequency).toFixed(2)} s`],["อัตราเร็วคลื่น",`${speed.toFixed(1)} m/s`]]} controls={<><Slider label="ความถี่" value={frequency} min={0.5} max={3} step={0.1} unit="Hz" onChange={v=>{clock.reset();setFrequency(v);}}/><Slider label="อัตราเร็วคลื่น" value={speed} min={2} max={6} step={0.2} unit="m/s" onChange={v=>{clock.reset();setSpeed(v);}}/><Slider label="แอมพลิจูด" value={amplitude} min={0.1} max={1} step={0.1} unit="m" onChange={setAmplitude}/><Playback clock={clock}/></>}>
 <line x1="50" y1="200" x2="670" y2="200" stroke="#b0bdaa"/><line x1="350" y1="80" x2="350" y2="320" stroke="#d5ab83" strokeDasharray="4 4"/><polyline points={points} fill="none" stroke="#345e48" strokeWidth="3"/><circle cx="350" cy={200-waveDisplacement(6,clock.time,amplitude,frequency,speed)*100} r="9" fill="#d66d3e"/>{[0,3,6,9,12].map(x=><text key={x} x={50+x*50} y="345" textAnchor="middle">{x} m</text>)}<text x="55" y="60">ยอดคลื่นเคลื่อนไปทางขวา →</text><line x1="50" y1="375" x2={50+wavelength*50} y2="375" stroke="#bb663f" strokeWidth="2"/><text x={50+wavelength*25} y="395" textAnchor="middle">λ = {wavelength.toFixed(2)} m</text><text x="6" y="105">+1 m</text><text x="6" y="305">−1 m</text></Frame>;
}
function RefractionLab(){
 const [n1,setN1]=useState(1),[n2,setN2]=useState(1.5),[incident,setIncident]=useState(35);const refracted=refractedAngle(n1,n2,incident),theta=incident*Math.PI/180;const media=[{name:"อากาศ",n:1},{name:"น้ำ",n:1.33},{name:"แก้ว",n:1.5}];
 return <Frame title="การหักเหและการสะท้อนกลับหมด" stats={[["มุมตกกระทบ",`${incident}°`],["มุมหักเห",refracted===null?"ไม่มีรังสีหักเห":`${refracted.toFixed(1)}°`],["มุมวิกฤต",n1>n2?`${(Math.asin(n2/n1)*180/Math.PI).toFixed(1)}°`:"ไม่มีในทิศนี้"]]} controls={<><label htmlFor="medium-one">ตัวกลางด้านบน</label><select id="medium-one" value={n1} onChange={e=>setN1(Number(e.target.value))}>{media.map(m=><option key={m.n} value={m.n}>{m.name} · n = {m.n}</option>)}</select><label htmlFor="medium-two">ตัวกลางด้านล่าง</label><select id="medium-two" value={n2} onChange={e=>setN2(Number(e.target.value))}>{media.map(m=><option key={m.n} value={m.n}>{m.name} · n = {m.n}</option>)}</select><Slider label="มุมตกกระทบ" value={incident} min={0} max={80} unit="°" onChange={setIncident}/><p className="hint">{refracted===null?"เกิดการสะท้อนกลับหมด แสงกลับสู่ตัวกลางเดิม":"มุมวัดจากเส้นประแนวตั้ง ไม่ใช่จากผิวรอยต่อ"}</p></>}>
 <rect x="30" y="30" width="660" height="180" fill="#f1f4e9"/><rect x="30" y="210" width="660" height="180" fill="#dceeea"/><line x1="30" y1="210" x2="690" y2="210" stroke="#6e998d"/><line x1="360" y1="25" x2="360" y2="390" stroke="#8ca693" strokeDasharray="6 6"/><Arrow x1={360-170*Math.sin(theta)} y1={210-170*Math.cos(theta)} x2={360} y2={210}/>{n1!==n2&&<Arrow x1={360} y1={210} x2={360+170*Math.sin(theta)} y2={210-170*Math.cos(theta)} color={refracted===null?"#ca663e":"#9caf8c"}/>}{refracted!==null&&<Arrow x1={360} y1={210} x2={360+170*Math.sin(refracted*Math.PI/180)} y2={210+170*Math.cos(refracted*Math.PI/180)} color="#216859"/>}<text x="50" y="65">n₁ = {n1}</text><text x="50" y="365">n₂ = {n2}</text><text x="420" y="90">{n1===n2?"ดัชนีเท่ากัน: แสงตรงต่อไป":"รังสีสะท้อน"}</text><text x="405" y="355">{refracted===null?"สะท้อนกลับหมด":"รังสีหักเห"}</text></Frame>;
}
function CircuitLab(){
 const [voltage,setVoltage]=useState(6),[r1,setR1]=useState(10),[r2,setR2]=useState(10),[parallel,setParallel]=useState(false);const clock=useClock(),model=resistorCircuit(voltage,r1,r2,parallel);
 function dots(y:number,current:number){return Array.from({length:7},(_,i)=><circle key={i} cx={(parallel?190:140)+((clock.time*current*0.25+i/7)%1)*(parallel?390:440)} cy={y} r="4" fill="#d47748"/>);}
 return <Frame title="วงจรตัวต้านทานสองตัว" stats={[["ความต้านทานรวม",`${model.resistance.toFixed(2)} Ω`],["กระแสรวม",`${model.total.toFixed(2)} A`],["กำลังรวม",`${(voltage*model.total).toFixed(2)} W`]]} controls={<><label htmlFor="circuit-kind">การต่อวงจร</label><select id="circuit-kind" value={parallel?"parallel":"series"} onChange={e=>{clock.reset();setParallel(e.target.value==="parallel");}}><option value="series">อนุกรม</option><option value="parallel">ขนาน</option></select><Slider label="แรงดันแหล่งจ่าย" value={voltage} min={0} max={12} unit="V" onChange={setVoltage}/><Slider label="ความต้านทาน R₁" value={r1} min={5} max={50} unit="Ω" onChange={setR1}/><Slider label="ความต้านทาน R₂" value={r2} min={5} max={50} unit="Ω" onChange={setR2}/><Playback clock={clock}/><p className="muted">จุดสีส้มแสดงทิศกระแสตามข้อตกลงเชิงสัญลักษณ์</p></>}>
 <path d="M100 150V80H620V320H100V230" fill="none" stroke="#345e48" strokeWidth="4"/><line x1="70" y1="170" x2="130" y2="170" stroke="#345e48" strokeWidth="5"/><line x1="83" y1="210" x2="117" y2="210" stroke="#345e48" strokeWidth="5"/><line x1="100" y1="150" x2="100" y2="170" stroke="#345e48" strokeWidth="4"/><line x1="100" y1="210" x2="100" y2="230" stroke="#345e48" strokeWidth="4"/><text x="50" y="145">+</text><text x="50" y="235">−</text><text x="40" y="270">{voltage} V</text>
 {parallel?<><path d="M180 80V220H620" fill="none" stroke="#345e48" strokeWidth="4"/><rect x="305" y="62" width="110" height="36" rx="4" fill="#e0e7ca" stroke="#345e48"/><rect x="305" y="202" width="110" height="36" rx="4" fill="#e0e7ca" stroke="#345e48"/><text x="360" y="86" textAnchor="middle">R₁ {r1} Ω</text><text x="360" y="226" textAnchor="middle">R₂ {r2} Ω</text><text x="340" y="130">I₁ = {model.i1.toFixed(2)} A</text><text x="340" y="270">I₂ = {model.i2.toFixed(2)} A</text>{model.i1>0&&dots(80,model.i1)}{model.i2>0&&dots(220,model.i2)}</>:<><rect x="230" y="62" width="100" height="36" rx="4" fill="#e0e7ca" stroke="#345e48"/><rect x="445" y="62" width="100" height="36" rx="4" fill="#e0e7ca" stroke="#345e48"/><text x="280" y="86" textAnchor="middle">R₁ {r1} Ω</text><text x="495" y="86" textAnchor="middle">R₂ {r2} Ω</text><text x="225" y="145">V₁ = {model.v1.toFixed(2)} V</text><text x="445" y="145">V₂ = {model.v2.toFixed(2)} V</text><text x="290" y="240">I₁ = I₂ = {model.total.toFixed(2)} A</text>{model.total>0&&dots(80,model.total)}</>}<text x="200" y="370">{parallel?"แรงดันแต่ละแขนงเท่ากับแหล่งจ่าย":"แรงดันทั้งสองตัวรวมเท่ากับแหล่งจ่าย"}</text></Frame>;
}
function HeatLab(){
 const [t1,setT1]=useState(80),[t2,setT2]=useState(20),[m1,setM1]=useState(1),[m2,setM2]=useState(1);const final=mixedTemperature(m1,t1,m2,t2),energy=Math.abs(m1*4200*(t1-final));
 function glass(x:number,t:number,m:number,label:string){const h=50+m*35;return <g><rect x={x} y="95" width="125" height="215" rx="10" fill="#f6f8f3" stroke="#9aac9b" strokeWidth="2"/><rect x={x+5} y={305-h} width="115" height={h} rx="5" fill={`hsl(${220-t*2.1} 55% 70%)`}/><text x={x+62} y="65" textAnchor="middle">{label}</text><text x={x+62} y="335" textAnchor="middle">{m.toFixed(1)} kg</text><text x={x+62} y="275" textAnchor="middle" className="temperature-label">{t.toFixed(1)}°C</text></g>;}
 return <Frame title="อุณหภูมิสมดุลหลังผสมน้ำ" stats={[["อุณหภูมิสุดท้าย",`${final.toFixed(1)} °C`],["มวลรวม",`${(m1+m2).toFixed(1)} kg`],["พลังงานที่ถ่ายโอน",`${(energy/1000).toFixed(2)} kJ`]]} controls={<><Slider label="อุณหภูมิแก้ว A" value={t1} min={5} max={95} unit="°C" onChange={setT1}/><Slider label="มวลน้ำ A" value={m1} min={0.2} max={2} step={0.2} unit="kg" onChange={setM1}/><Slider label="อุณหภูมิแก้ว B" value={t2} min={5} max={95} unit="°C" onChange={setT2}/><Slider label="มวลน้ำ B" value={m2} min={0.2} max={2} step={0.2} unit="kg" onChange={setM2}/><p className="hint">ปรับค่าเพื่อเห็นผลก่อน–หลังทันที · น้ำมวลเท่ากันจึงใช้ค่าเฉลี่ยอุณหภูมิธรรมดาได้</p></>} note="สีแสดงอุณหภูมิ ระดับน้ำแสดงมวลเชิงสัญลักษณ์ · cน้ำ = 4200 J/(kg·K)">{glass(40,t1,m1,"ก่อนผสม A")}{glass(245,t2,m2,"ก่อนผสม B")}<text x="195" y="200" textAnchor="middle" className="big-symbol">+</text><Arrow x1={400} y1={200} x2={475} y2={200}/>{glass(515,final,m1+m2,"หลังสมดุล")}</Frame>;
}
function QuantumLab(){
 const [n,setN]=useState(1),[length,setLength]=useState(1),[end,setEnd]=useState(50);const path=Array.from({length:301},(_,i)=>`${60+i*2},${315-boxDensity(i/300,n)*110}`).join(" ");const shade=["60,315",...Array.from({length:151},(_,i)=>{const x=end/100*i/150;return `${60+x*600},${315-boxDensity(x,n)*110}`;}),`${60+end*6},315`].join(" ");
 return <Frame title="บ่อศักย์อนันต์: ความหนาแน่นความน่าจะเป็น" stats={[["พลังงานสถานะ",`${boxEnergyEV(n,length).toFixed(3)} eV`],["โอกาสในพื้นที่สีส้ม",`${(boxProbability(0,end/100,n)*100).toFixed(1)} %`],["จุดศูนย์ภายใน",`${n-1} จุด`]]} controls={<><Slider label="เลขควอนตัม n" value={n} min={1} max={5} onChange={setN}/><Slider label="ความกว้างกล่อง L" value={length} min={0.5} max={3} step={0.1} unit="nm" onChange={setLength}/><Slider label="ช่วงที่ตรวจจากซ้าย" value={end} min={0} max={100} unit="% ของ L" onChange={setEnd}/><p className="hint">พื้นที่ใต้กราฟในช่วงสีส้มคือโอกาสพบอนุภาค ไม่ใช่เส้นทางการเคลื่อนที่</p></>} note="สถานะพลังงานแน่นอนมีความหนาแน่นไม่เปลี่ยนตามเวลา · ภาพขยายกล่องให้กว้างเท่ากันเพื่อเปรียบเทียบรูปทรง"><rect x="40" y="65" width="20" height="250" fill="#697e6e"/><rect x="660" y="65" width="20" height="250" fill="#697e6e"/><polygon points={shade} fill="#efd2b9"/><line x1="60" y1="315" x2="660" y2="315" stroke="#69856b"/><polyline points={path} fill="none" stroke="#315e48" strokeWidth="3"/><text x="70" y="40">L|ψ|²</text><text x="60" y="347" textAnchor="middle">0</text><text x="360" y="347" textAnchor="middle">0.5</text><text x="660" y="347" textAnchor="middle">1</text><text x="360" y="380" textAnchor="middle">ตำแหน่งสัมพัทธ์ x/L · L = {length.toFixed(1)} nm</text><text x="12" y="100">2</text><text x="12" y="320">0</text></Frame>;
}
export function VisualLab({id}:{id:Exclude<SimulationId,"projectile">}){const components={"web-swing":WebSwingLab,coaster:CoasterLab,buoyancy:BuoyancyLab,pressure:PressureLab,barometer:TorricelliLab,orbit:OrbitLab,"three-body":ThreeBodyLab,force:ForceLab,pendulum:PendulumLab,wave:WaveLab,refraction:RefractionLab,"double-slit":YoungLab,spectrum:SpectrumLab,rutherford:RutherfordLab,circuit:CircuitLab,heat:HeatLab,quantum:QuantumLab,osmosis:OsmosisLab,"acid-base":AcidBaseLab,elements:ElementsLab,incline:InclineLab,collision:CollisionLab,lens:LensLab,motor:MotorLab,"half-life":HalfLifeLab,enzyme:EnzymeLab,photosynthesis:PhotosynthesisLab,mendel:MendelLab,"predator-prey":PredatorPreyLab,"reaction-rate":ReactionRateLab,equilibrium:EquilibriumLab,"ideal-gas":IdealGasLab,titration:TitrationLab,braking:BrakingLab,lift:LiftLab,torque:TorqueLab,linear:LinearLab,quadratic:QuadraticLab,exponential:ExponentialLab,absolute:AbsoluteLab,reciprocal:ReciprocalLab,sine:SineLab,trigonometry:TrigonometryLab,probability:ProbabilityLab,area:AreaLab,doppler:DopplerLab,coulomb:CoulombLab,conduction:ConductionLab,dna:DnaLab,foucault:FoucaultLab,brownian:BrownianLab,oersted:OerstedLab,magnet:MagnetLab,lorentz:LorentzLab,faraday:FaradayLab,bond:BondLab,ionic:IonicLab,lewis:LewisLab};const Component=components[id];return <Component/>;}
